# -*- coding: utf-8 -*-
"""Đồ_án_cuối_kì_môn_Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/115DiV3fQKErbrsV49vzznwVYza1RJmxa

#Đồ án môn Python

#19110348 - Đỗ Khánh Đăng Khoa (Crawl dữ liệu)
"""

import requests
from bs4 import BeautifulSoup
import csv
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

"""##**TOTOSHOP**"""

del str
link_base2="https://totoshop.vn/do-nam-pc72882.html?page="
list_link02=[]
for one in range(1,18):
  item02=link_base2+ str(one)
  list_link02.append(item02)
list_link02

count=0
with open('output1.csv', 'w') as f2:   #tạo một file csv và ghi dữ liệu khi crawl vào file
    Name2='Name'
    Img2='Image'
    Price2='Price'
    fields2 =f"{Name2},{Img2},{Price2},\n"   #tạo các tên trường lưu dữ liệu
    f2.write(fields2)  #ghi vào file csv
    headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}
    for i in range(len(list_link02)):   #dùng vòng for để crawl tất cả các sản phẩm của từng trang web lưu trong list_link
      link02 = list_link02[i]
      r2= requests.get(link02,headers=headers)   #thực hiện gửi yêu cầu GET đến URL đang xét (một số web ktra robot fake id lại bằng cách dùng header)
      crawl02=BeautifulSoup(r2.text,'html.parser')   #dùng thư viện BeautifulSoup để lấy dữ liệu ra khỏi HTML
      product_data02=crawl02.find_all("div", class_="grid--metro__item grid__item one-whole medium--one-third large-up--one-quarter small--two-quarters")
      #sử dụng find_all để tìm tất cả các sản phẩm có trong class của thẻ div và lưu nó thành 1 sản phẩm (product_data)
      for j in product_data02:
        I_mg02 = j.find('a').find('img')['data-src']   #tìm kiếm đường link ảnh trong product_data đã lưu trên
        img02=I_mg02.replace(" ","")   #lọc nhiễu dữ liệu
        N_ame02=j.find('a').find('img')['alt']   #tìm kiếm tên sản phẩm trong product_data đã lưu trên
        P_rice02 = j.find(class_="product-price--current tp_product_price").text   #tìm kiếm giá sản phẩm trong product_data đã tìm kiếm trên
        price02=P_rice02.replace(" ","").replace(",","")
        str=f"{N_ame02},{img02}, {price02},\n" 
        count+=1
        f2.write(str)
print(count)   #đếm các sản phẩm đã thu được khi crawl

"""##**SHOP BOUTIQUE**"""

del str
link_base="https://360boutique.vn/cua-hang/"  
list_link=[]
#lấy tất cả trang web của shop lưu vào mảng list_link
for one in range(1,23):
  item=link_base+ 'page/'+ str(one)
  list_link.append(item)
#list_link

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}
count=0
with open('output2.csv', 'w') as f1: 
    Name1='Name' 
    Img1='Image'
    Price1='Price'
    fields =f"{Name1},{Img1},{Price1},\n"  
    f1.write(fields)     
    for i in range(len(list_link)):  
      link = list_link[i]
      r= requests.get(link,headers=headers)  
      crawl=BeautifulSoup(r.text,'html.parser')  
      product_data=crawl.find_all("div", class_="col-md-3 col-sm-6 col-xs-6 pro-loop col-5")  
      for j in product_data:
        I_mg = j.find('a').find('img')['src']   
        img=I_mg.replace(" ","")    
        N_ame  = j.find('a').find('img')['alt'] 
        name=N_ame.replace('Bảo vệ: ','') 
        price = j.find('p').find('bdi').text  
        str=f"{name},{img}, {price},\n" 
        print(str)
        count=count+1
        f1.write(str)
print(count)

"""##**ROUTINE**"""

del str
link_base3="https://routine.vn/thoi-trang-nam.html?p="
list_link03=[]
for one in range(1,21):
  item02=link_base3+ str(one)
  list_link03.append(item02)
#list_link03

count=0
with open('output3.csv', 'w') as f3:
    Name3='Name'
    Img3='Image'
    Price3='Price'
    fields3 =f"{Name3},{Img3},{Price3},\n"
    f3.write(fields3)
    headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}
    for i in range(len(list_link03)):
      link03 = list_link03[i]
      r3= requests.get(link03,headers=headers)  # một số web ktra robot fake id lại = header
      crawl03=BeautifulSoup(r3.text,'html.parser')
      product_data03=crawl03.find_all("div", class_="product-item-info")
      for j in product_data03:
          I_mg03 = j.find('a').find('img')['data-src']
          img03=I_mg03.replace(" ","") 
          N_ame03=j.find('a').find('img')['alt']
          name03=N_ame03.replace(",","").replace(".","")
          P_rice03 = j.find(class_="price-wrapper").text
          price03=P_rice03.replace("\xa0","")
          str=f"{name03},{img03}, {price03},\n" 
          #print(str)
          count+=1
          f3.write(str)
print(count)

#In ảnh từ link để ktra
from PIL import Image
import requests
from io import BytesIO
response = requests.get('https://360boutique.vn/wp-content/uploads/2018/08/G1011-750k-1-copy-Copy-400x600.jpg')
img = Image.open(BytesIO(response.content))
new_width  = 200
new_height = 300
img = img.resize((new_width, new_height), Image.ANTIALIAS)
img

"""##**Lưu data dưới dạng dataframe**"""

dataset= pd.read_csv('/content/x2.csv')
dataset.shape
data = dataset[['Name','Image','Price','PhanLoai','Quan jogger','Quan au','Ao thun nam','Ao khoac','Ao so mi','Ao hoodie' ]]

data

#Lọc nhiễu
for i in range((len(data[['Price']]))):
       data['Price'][i]=data['Price'][i].replace(" ","")

data['Price'][1]

"""#19110315 - Trịnh Ngọc Hiến (Vẽ biểu đồ)


"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""##Hàm vẽ biểu đồ tròn
- title: Tiêu đề biểu đồ.
- Các mặt hàng: (tên) các sản phẩm.
- Dữ liệu: (data) của các sản phẩm.

"""

def ve_bieu_do_tron(title, cac_mat_hang, dulieu):
  fig = plt.figure()
  ax = fig.add_axes([0,0,1,1])
  ax.axis('equal')
  cac_mat_hang = cac_mat_hang
  bieu_do = dulieu
  ax.pie(bieu_do, labels = cac_mat_hang, autopct='%0.2f%%')
  plt.title(title)
  plt.show()

"""##Hàm vẽ biểu đồ cột
- title: Tiêu đề biểu đồ.
- color: màu sắc của các cột thành phần.
- Các mặt hàng: (tên) các sản phẩm.
- Dữ liệu: (data) của các sản phẩm.
- xlabel: tên của cột X.
- ylabel: tên của cột Y.
- rotation: Độ xoay của các chú thích ở cột x
"""

#Hàm chú thích:
def addlabels(x,y):
    for i in range(len(x)):
        plt.text(i,y[i],y[i],horizontalalignment = 'center',fontsize = 14)

#Hàm vẽ biểu đồ cột
def ve_bieu_do_cot(title, colors, cac_mat_hang, dulieu, xlabel, ylabel, rotation):
  New_Colors = colors
  plt.bar(cac_mat_hang, dulieu, color=New_Colors)
  plt.title(title, fontsize=14)
  plt.xlabel(xlabel, fontsize=14)
  plt.ylabel(ylabel, fontsize=14)
  addlabels(cac_mat_hang,dulieu)
  plt.xticks(rotation = rotation)
  plt.show()

"""##Dữ liệu của 3 shop: Boutique Shop - ToTo Shop - Routine Shop 
- Boutique Shop (x1.csv)
- ToTo Shop (x2.csv)
- Routine Shop (x3.csv)

###Shop Boutique

####Xử lý dữ liệu từ file 'x1.csv'.
"""

data = 'x1.csv'
path = pd.read_csv(data)
df = pd.DataFrame(path)
df

moving_column = df.pop('PhanLoai')
df.insert(1,'PhanLoai', moving_column)
df.head()

#Tạo cột Giá thành để loại bỏ "đ" trong price
df['GiaThanh'] = ''
df['GiaThanh'] = df['Price'].str[:-1]


#Đưa giá trị từ object về int
for i in range(len(df['GiaThanh'])):
  df['GiaThanh'][i]=df['Price'].str[:-1][i].replace(" ","")

for i in range(len(df['GiaThanh'])):
  df['GiaThanh'][i]=df['Price'].str[:-1][i].replace(".","")
 
#Ép kiểu cột Giá Thành thành int
df['GiaThanh'] = df['GiaThanh'].astype(int)

df.head()

print(df['GiaThanh'].dtype)

"""####Tính số sản phẩm là Áo, Quần, hay SP khác.
0 là áo, 1 là quần, 2 là sản phẩm còn lại.
"""

count_ao = 0
for i in df['PhanLoai']:
  if i == 0:
    count_ao = count_ao+1

print('SL áo của dữ liệu: ',count_ao)

count_quan = 0
for i in df['PhanLoai']:
  if i == 1:
    count_quan = count_quan + 1

print('SL quần của dữ liệu: ',count_quan)

count_other = 0
for i in df['PhanLoai']:
  if i == 2:
    count_other = count_other + 1
  

print('SL các sản phẩm khác của dữ liệu: ',count_other)

sum = count_ao + count_quan + count_other
print(sum)

"""####Biểu đồ tròn về các mặt hàng chủ yếu của shop."""

#Tính % của Áo, Quần và các sản phẩm khác:

percent_ao_0 = (count_ao*100)/sum
print('% áo: ',percent_ao_0)

percent_quan_0 = (count_quan*100)/sum
print('% quần: ',percent_quan_0)

percent_other_0 = (count_other*100)/sum
print('% sp khác: ',percent_other_0)

from matplotlib import pyplot as plt
import numpy as np

cac_mat_hang = ['Áo', 'Quần', 'Các mặt hàng khác']
title = 'Các mặt hàng chủ yếu của Shop Boutique'
dulieu = [percent_ao_0, percent_quan_0, percent_other_0]
ve_bieu_do_tron(title, cac_mat_hang, dulieu)

"""####Biểu đồ cột về số lượng các mặt hàng chủ yếu của Boutique Shop."""

#Biểu đồ cột về số lượng các mặt hàng chủ yếu của Boutique Shop:
sanpham = ['Áo', 'Quần', 'Các mặt hàng khác']
soluong = [count_ao, count_quan, count_other]
xlabel = 'Các mặt hàng'
ylabel = 'Số lượng'
title = 'Số lượng các mặt hàng chủ yếu của Shop Boutique'
colors = ['orange', 'green', 'purple']
rotate = 0

ve_bieu_do_cot(title, colors, sanpham, soluong, xlabel, ylabel,rotate)

"""####Biểu đồ cột thể hiện xấp xỉ giá thành của các sản phẩm."""

#Đếm số lượng sản phẩm của Boutique Shop trog các khoảng:

count_0 = 0 #Giá thành: 100k - 200k
count_1 = 0 #Giá thành: 200k - 300k
count_2 = 0 #Giá thành: 300k - 400k
count_3 = 0 #Giá thành: 400k - 500k
count_4 = 0 #Giá thành: 500k - 600k
count_5 = 0 #Giá thành: 600k - 700k
count_6 = 0 #Giá thành: 700k - 800k
count_7 = 0 #Giá thành: 800k - 900k
count_8 = 0 #Giá thành: 900k - 1000k
count_9 = 0 #Giá thành: 1000k trở lên
for i in df['GiaThanh']:
  if i > 0 and i < 200000:
    count_0 = count_0 + 1  
  if i >= 200000 and i < 300000:
    count_1 = count_1 + 1
  if i >= 300000 and i < 400000:
    count_2 = count_2 + 1
  if i >= 400000 and i < 500000:
    count_3 = count_3 + 1
  if i >= 500000 and i < 600000:
    count_4 = count_4 + 1
  if i >= 600000 and i < 700000:
    count_5 = count_5 + 1
  if i >= 700000 and i < 800000:
    count_6 = count_6 + 1
  if i >= 800000 and i < 900000:
    count_7 = count_7 + 1
  if i >= 900000 and i < 1000000:
    count_8 = count_8 + 1
  if i >= 1000000:
    count_9 = count_9 + 1
  
print(count_0)
print(count_1)
print(count_2)
print(count_3)
print(count_4)
print(count_5)
print(count_6)
print(count_7)
print(count_8)
print(count_9)
sum = count_0 + count_1 + count_2 + count_3 + count_4 +\
      count_5 + count_6 + count_7 + count_8 + count_9
print(sum)
print('Giá thành cao nhất của shop: ',df['GiaThanh'].min())
print('Giá thành thấp nhất của shop: ', df['GiaThanh'].max())

#Biểu đồ cột thể hiện xấp xỉ giá thành của các sản phẩm:

giathanh = ['0 - 100k', '100k - 200k', '200k - 300k', '300k - 400k', 
            '400k - 500k', '500k - 600k', '600k - 700k', '700k - 800k',
            '900k - 1000k', '1000k trở lên']

khoang = [count_0, count_1, count_2, count_3, count_4, 
          count_5, count_6, count_7, count_8, count_9
          ]
          
title = 'Giá thành xấp xỉ của các sản phẩm Shop Boutique'
xlabel = 'Các khoảng'
ylabel = 'Giá thành'
colors = ['green']
rotate = 45


ve_bieu_do_cot(title, colors, giathanh, khoang, xlabel, ylabel, rotate)

"""####Thống kê về các mặt hàng là quần áo của Shop."""

#Đếm số sản phẩm là Quần Jogger
count_jogger = 0
df['Quan jogger']
for jogger in df['Quan jogger']:
  if jogger == 1:
   count_jogger = count_jogger + 1

print('SL quần jogger: ',count_jogger)

#Đếm số sản phẩm là Quần jean
count_jean = 0

for jean in df['Quan jean']:
  if jean == 1:
   count_jean = count_jean + 1

print('SL quần jean: ',count_jean)

#Đếm số sản phẩm là Quần âu
count_au = 0

for au in df['Quan au']:
  if au == 1:
   count_au = count_au + 1

print('SL quần âu: ',count_au)

#Đếm số sản phẩm là Áo thun nam:
count_aothun = 0

for aothun in df['Ao thun nam']:
  if aothun == 1:
   count_aothun = count_aothun + 1

print('SL áo thun: ',count_aothun)

#Đếm số sản phẩm là Áo khoác:
count_aokhoac = 0

for aokhoac in df['Ao khoac']:
  if aokhoac == 1:
   count_aokhoac = count_aokhoac + 1

print('SL áo khoác: ',count_aokhoac)

#Đếm số sản phẩm là Áo sơ mi:
count_somi = 0

for somi in df['Ao so mi']:
  if somi == 1:
   count_somi = count_somi + 1

print('SL áo sơ mi: ',count_somi)

#Đếm số sản phẩm là Áo hoodie:
count_hoodie = 0

for hoodie in df['Ao hoodie']:
  if hoodie == 1:
   count_hoodie = count_hoodie + 1

print('SL áo hoodie: ',count_hoodie)

#Thống kê về các mặt hàng là quần áo của Shop 

loai_sp = ['Quần Jogger', 'Quần Jean', 'Quần Âu', 
           'Áo thun nam', 'Áo Khoác', 'Áo sơ mi', 'Áo Hoodie'
           ]

soluong = [count_jogger, count_jean, count_au,
          count_aothun, count_aokhoac, count_somi, count_hoodie
          ]
colors = ['purple']
title = 'Thống kê về các mặt hàng là Quần - Áo của Shop Boutique'
xlabel = 'Các loại sản phẩm'
ylabel = 'Số lượng'
rotate = 45

ve_bieu_do_cot(title, colors, loai_sp, soluong, xlabel, ylabel, rotate)



"""###Shop ToTo

####Xử lý dữ liệu từ file 'x2.csv'.
"""

data1 = 'x2.csv'
path1 = pd.read_csv(data1)
df1 = pd.DataFrame(path1)
df1

moving_column = df1.pop('PhanLoai')
df1.insert(1,'PhanLoai', moving_column)
df1

#Tạo cột Giá thành để loại bỏ "đ" trong price
#Xóa các dấu "." và khoảng cách trong cột Price
df1['GiaThanh'] = ''
df1['GiaThanh'] = df1['Price'].str[:-1]

#Đưa giá trị từ object về int
for i in range(len(df1['GiaThanh'])):
  df1['GiaThanh'][i]=df1['Price'].str[:-1][i].replace(" ","")

for i in range(len(df1['GiaThanh'])):
  df1['GiaThanh'][i]=df1['Price'].str[:-1][i].replace(".","")

#Ép kiểu cột Giá Thành thành int
df1['GiaThanh'] = df1['GiaThanh'].astype(int)

print(df1['GiaThanh'].dtype)

"""####Tính số sản phẩm là Áo, Quần, hay SP khác.
0 là áo, 1 là quần, 2 là sản phẩm còn lại.
"""

count_ao_1 = 0
for i in df1['PhanLoai']:
  if i == 0:
    count_ao_1 = count_ao_1 + 1

print('SL áo của dữ liệu: ',count_ao_1)

count_quan_1 = 0
for i in df1['PhanLoai']:
  if i == 1:
    count_quan_1 = count_quan_1 + 1

print('SL quần của dữ liệu: ',count_quan_1)

count_other_1 = 0
for i in df1['PhanLoai']:
  if i == 2:
    count_other_1 = count_other_1 + 1
  

print('SL các sản phẩm khác của dữ liệu: ',count_other_1)

sum = count_ao_1 + count_quan_1 + count_other_1
print(sum)

"""####Biểu đồ tròn về các mặt hàng chủ yếu của shop."""

#Tính % của Áo, Quần và các sản phẩm khác của ToTo Shop:

percent_ao_1 = (count_ao_1*100)/sum
print('% áo: ',percent_ao_1)

percent_quan_1 = (count_quan_1*100)/sum
print('% quần: ',percent_quan_1)

percent_other_1 = (count_other_1*100)/sum
print('% sp khác: ',percent_other_1)

from matplotlib import pyplot as plt
import numpy as np

cac_mat_hang = ['Áo', 'Quần']
title = 'Các mặt hàng chủ yếu của Shop ToTo'
dulieu = [percent_ao_1, percent_quan_1]
ve_bieu_do_tron(title, cac_mat_hang, dulieu)

"""####Biểu đồ cột về số lượng các mặt hàng chủ yếu của shop."""

#Biểu đồ cột về số lượng các mặt hàng chủ yếu của ToTo Shop:
sanpham = ['Áo', 'Quần', 'Các mặt hàng khác']
soluong = [count_ao_1, count_quan_1, count_other_1]
xlabel = 'Các mặt hàng'
ylabel = 'Số lượng'
title = 'Số lượng các mặt hàng chủ yếu của Shop ToTo'
colors = ['orange', 'green', 'purple']
rotate = 0

ve_bieu_do_cot(title, colors, sanpham, soluong, xlabel, ylabel,rotate)

"""####Biểu đồ cột thể hiện xấp xỉ giá thành của các sản phẩm."""

#Đếm giá thành sản phẩm của Boutique Shop trog các khoảng:

count_0 = 0 #Giá thành: 100k - 200k
count_1 = 0 #Giá thành: 200k - 300k
count_2 = 0 #Giá thành: 300k - 400k
count_3 = 0 #Giá thành: 400k - 500k
count_4 = 0 #Giá thành: 500k - 600k
count_5 = 0 #Giá thành: 600k - 700k
count_6 = 0 #Giá thành: 700k - 800k
count_7 = 0 #Giá thành: 800k - 900k
count_8 = 0 #Giá thành: 900k - 1000k
count_9 = 0 #Giá thành: 1000k trở lên
for i in df1['GiaThanh']:
  if i > 0 and i < 200000:
    count_0 = count_0 + 1  
  if i >= 200000 and i < 300000:
    count_1 = count_1 + 1
  if i >= 300000 and i < 400000:
    count_2 = count_2 + 1
  if i >= 400000 and i < 500000:
    count_3 = count_3 + 1
  if i >= 500000 and i < 600000:
    count_4 = count_4 + 1
  if i >= 600000 and i < 700000:
    count_5 = count_5 + 1
  if i >= 700000 and i < 800000:
    count_6 = count_6 + 1
  if i >= 800000 and i < 900000:
    count_7 = count_7 + 1
  if i >= 900000 and i < 1000000:
    count_8 = count_8 + 1
  if i >= 1000000:
    count_9 = count_9 + 1
  
print(count_0)
print(count_1)
print(count_2)
print(count_3)
print(count_4)
print(count_5)
print(count_6)
print(count_7)
print(count_8)
print(count_9)
sum = count_0 + count_1 + count_2 + count_3 + count_4 +\
      count_5 + count_6 + count_7 + count_8 + count_9
print(sum)
print('Giá thành cao nhất của shop: ',df1['GiaThanh'].min())
print('Giá thành thấp nhất của shop: ', df1['GiaThanh'].max())

#Biểu đồ cột thể hiện xấp xỉ giá thành của các sản phẩm:

giathanh = ['0 - 100k', '100k - 200k', '200k - 300k', '300k - 400k', 
            '400k - 500k', '500k - 600k', '600k - 700k', '700k - 800k',
            '900k - 1000k', '1000k trở lên']

khoang = [count_0, count_1, count_2, count_3, count_4, 
          count_5, count_6, count_7, count_8, count_9
          ]

title = 'Giá thành xấp xỉ của các sản phẩm Shop ToTo'
xlabel = 'Các khoảng'
ylabel = 'Giá thành'
colors = ['green']
rotate = 45

ve_bieu_do_cot(title, colors, giathanh, khoang, xlabel, ylabel, rotate)

"""####Thống kê về các mặt hàng là quần áo của Shop."""

#Đếm số sản phẩm là Quần Jogger
count_jogger_1 = 0
df['Quan jogger']
for jogger in df1['Quan jogger']:
  if jogger == 1:
   count_jogger_1 = count_jogger_1 + 1

print('SL quần jogger: ',count_jogger_1)

#Đếm số sản phẩm là Quần jean
count_jean_1 = 0

for jean in df1['Quan jean']:
  if jean == 1:
   count_jean_1 = count_jean_1 + 1

print('SL quần jeans: ',count_jean_1)

#Đếm số sản phẩm là Quần âu
count_au_1 = 0

for au in df1['Quan au']:
  if au == 1:
   count_au_1 = count_au_1 + 1

print('SL quần âu: ',count_au_1)

#Đếm số sản phẩm là Áo thun nam:
count_aothun_1 = 0

for aothun in df1['Ao thun nam']:
  if aothun == 1:
   count_aothun_1 = count_aothun_1 + 1

print('SL áo thun: ',count_aothun_1)

#Đếm số sản phẩm là Áo khoác:
count_aokhoac_1 = 0

for aokhoac in df1['Ao khoac']:
  if aokhoac == 1:
   count_aokhoac_1 = count_aokhoac_1 + 1

print('SL áo khoác: ',count_aokhoac_1)

#Đếm số sản phẩm là Áo sơ mi:
count_somi_1 = 0

for somi in df1['Ao so mi']:
  if somi == 1:
   count_somi_1 = count_somi_1 + 1

print('SL áo sơ mi: ',count_somi_1)

#Đếm số sản phẩm là Áo hoodie:
count_hoodie_1 = 0

for hoodie in df1['Ao hoodie']:
  if hoodie == 1:
   count_hoodie_1 = count_hoodie_1 + 1

print('SL áo hoodie: ',count_hoodie_1)

#Thống kê về các mặt hàng là quần áo của Shop 

loai_sp = ['Quần Jogger', 'Quần Jean', 'Quần Âu', 
           'Áo thun nam', 'Áo Khoác', 'Áo sơ mi', 'Áo Hoodie'
           ]

soluong = [count_jogger_1, count_jean_1, count_au_1,
          count_aothun_1, count_aokhoac_1, count_somi_1, count_hoodie_1
          ]
colors = ['purple']
title = 'Thống kê về các mặt hàng là Quần - Áo của Shop ToTo'
xlabel = 'Các loại sản phẩm'
ylabel = 'Số lượng'
rotate = 45

ve_bieu_do_cot(title, colors, loai_sp, soluong, xlabel, ylabel, rotate)



"""###Shop Routine

####Xử lý dữ liệu từ file 'x3.csv'.
"""

data2 = 'x3.csv'
path2 = pd.read_csv(data2)
df2 = pd.DataFrame(path2)
df2

moving_column = df2.pop('PhanLoai')
df2.insert(1,'PhanLoai', moving_column)
df2

#Tạo cột Giá thành để loại bỏ "đ" trong price
#Xóa các dấu "." và khoảng cách trong cột Price
df2['GiaThanh'] = ''
df2['GiaThanh'] = df2['Price'].str[:-1]

#Đưa giá trị từ object về int
for i in range(len(df2['GiaThanh'])):
  df2['GiaThanh'][i]=df2['Price'].str[:-1][i].replace(" ","")

for i in range(len(df2['GiaThanh'])):
  df2['GiaThanh'][i]=df2['Price'].str[:-1][i].replace(".","")

#Ép kiểu cột Giá Thành thành int
df2['GiaThanh'] = df2['GiaThanh'].astype(int)

print(df2['GiaThanh'].dtype)

"""####Tính số sản phẩm là Áo, Quần, hay SP khác.
0 là áo, 1 là quần, 2 là sản phẩm còn lại.
"""

count_ao_2 = 0
for i in df2['PhanLoai']:
  if i == 0:
    count_ao_2 = count_ao_2 + 1

print('SL áo của dữ liệu: ',count_ao_2)

count_quan_2 = 0
for i in df2['PhanLoai']:
  if i == 1:
    count_quan_2 = count_quan_2 + 1

print('SL quần của dữ liệu: ',count_quan_2)

count_other_2 = 0
for i in df2['PhanLoai']:
  if i == 2:
    count_other_2 = count_other_2 + 1
  

print('SL các sản phẩm khác của dữ liệu: ',count_other_2)

sum = count_ao_2 + count_quan_2 + count_other_2
print(sum)

"""####Biểu đồ tròn về các mặt hàng chủ yếu của shop."""

#Tính % của Áo, Quần và các sản phẩm khác của ToTo Shop:

percent_ao_2 = (count_ao_2*100)/sum
print('% áo: ',percent_ao_2)

percent_quan_2 = (count_quan_2*100)/sum
print('% quần: ',percent_quan_2)

percent_other_2 = (count_other_2*100)/sum
print('% sp khác: ',percent_other_2)

from matplotlib import pyplot as plt
import numpy as np

cac_mat_hang = ['Áo', 'Quần','Các mặt hàng khác']
title = 'Các mặt hàng chủ yếu của Shop Routine'
dulieu = [percent_ao_2, percent_quan_2, percent_other_2]
ve_bieu_do_tron(title, cac_mat_hang, dulieu)

"""####Biểu đồ cột về số lượng các mặt hàng chủ yếu của shop."""

#Biểu đồ cột về số lượng các mặt hàng chủ yếu của ToTo Shop:
sanpham = ['Áo', 'Quần', 'Các mặt hàng khác']
soluong = [count_ao_2, count_quan_2, count_other_2]
xlabel = 'Các mặt hàng'
ylabel = 'Số lượng'
title = 'Số lượng các mặt hàng chủ yếu của Shop ToTo'
colors = ['orange', 'green', 'purple']
rotate = 0

ve_bieu_do_cot(title, colors, sanpham, soluong, xlabel, ylabel,rotate)

"""####Biểu đồ cột thể hiện xấp xỉ giá thành của các sản phẩm."""

#Đếm số lượng sản phẩm của Boutique Shop trog các khoảng:

count_0 = 0 #Giá thành: 100k - 200k
count_1 = 0 #Giá thành: 200k - 300k
count_2 = 0 #Giá thành: 300k - 400k
count_3 = 0 #Giá thành: 400k - 500k
count_4 = 0 #Giá thành: 500k - 600k
count_5 = 0 #Giá thành: 600k - 700k
count_6 = 0 #Giá thành: 700k - 800k
count_7 = 0 #Giá thành: 800k - 900k
count_8 = 0 #Giá thành: 900k - 1000k
count_9 = 0 #Giá thành: 1000k trở lên
for i in df2['GiaThanh']:
  if i > 0 and i < 200000:
    count_0 = count_0 + 1  
  if i >= 200000 and i < 300000:
    count_1 = count_1 + 1
  if i >= 300000 and i < 400000:
    count_2 = count_2 + 1
  if i >= 400000 and i < 500000:
    count_3 = count_3 + 1
  if i >= 500000 and i < 600000:
    count_4 = count_4 + 1
  if i >= 600000 and i < 700000:
    count_5 = count_5 + 1
  if i >= 700000 and i < 800000:
    count_6 = count_6 + 1
  if i >= 800000 and i < 900000:
    count_7 = count_7 + 1
  if i >= 900000 and i < 1000000:
    count_8 = count_8 + 1
  if i >= 1000000:
    count_9 = count_9 + 1
  
print(count_0)
print(count_1)
print(count_2)
print(count_3)
print(count_4)
print(count_5)
print(count_6)
print(count_7)
print(count_8)
print(count_9)
sum = count_0 + count_1 + count_2 + count_3 + count_4 +\
      count_5 + count_6 + count_7 + count_8 + count_9
print(sum)
print('Giá thành cao nhất của shop: ',df2['GiaThanh'].min())
print('Giá thành thấp nhất của shop: ', df2['GiaThanh'].max())

#Biểu đồ cột thể hiện xấp xỉ giá thành của các sản phẩm:

giathanh = ['0 - 100k', '100k - 200k', '200k - 300k', '300k - 400k', 
            '400k - 500k', '500k - 600k', '600k - 700k', '700k - 800k',
            '900k - 1000k', '1000k trở lên']

khoang = [count_0, count_1, count_2, count_3, count_4, 
          count_5, count_6, count_7, count_8, count_9
          ]
          
title = 'Giá thành xấp xỉ của các sản phẩm Shop Routine'
xlabel = 'Các khoảng'
ylabel = 'Giá thành'
colors = ['green']
rotate = 45


ve_bieu_do_cot(title, colors, giathanh, khoang, xlabel, ylabel, rotate)

"""####Thống kê về các mặt hàng là quần áo của Shop."""

#Đếm số sản phẩm là Quần Jogger
count_jogger_2 = 0
df['Quan jogger']
for jogger in df2['Quan jogger']:
  if jogger == 1:
   count_jogger_2 = count_jogger_2 + 1

print('SL quần jogger: ',count_jogger_2)

#Đếm số sản phẩm là Quần jean
count_jean_2 = 0

for jean in df2['Quan jean']:
  if jean == 1:
   count_jean_2 = count_jean_2 + 1

print('SL quần jeans: ',count_jean_2)

#Đếm số sản phẩm là Quần âu
count_au_2 = 0

for au in df2['Quan au']:
  if au == 1:
   count_au_2 = count_au_2 + 1

print('SL quần âu: ',count_au_2)

#Đếm số sản phẩm là Áo thun nam:
count_aothun_2 = 0

for aothun in df2['Ao thun nam']:
  if aothun == 1:
   count_aothun_2 = count_aothun_2 + 1

print('SL áo thun: ',count_aothun_2)

#Đếm số sản phẩm là Áo khoác:
count_aokhoac_2 = 0

for aokhoac in df2['Ao khoac']:
  if aokhoac == 1:
   count_aokhoac_2 = count_aokhoac_2 + 1

print('SL áo khoác: ',count_aokhoac_2)

#Đếm số sản phẩm là Áo sơ mi:
count_somi_2 = 0

for somi in df2['Ao so mi']:
  if somi == 1:
   count_somi_2 = count_somi_2 + 1

print('SL áo sơ mi: ',count_somi_2)

#Đếm số sản phẩm là Áo hoodie:
count_hoodie_2 = 0

for hoodie in df2['Ao hoodie']:
  if hoodie == 1:
   count_hoodie_2 = count_hoodie_2 + 1

print('SL áo hoodie: ',count_hoodie_2)

loai_sp = ['Quần Jogger', 'Quần Jean', 'Quần Âu', 
           'Áo thun nam', 'Áo Khoác', 'Áo sơ mi', 'Áo Hoodie'
           ]

soluong = [count_jogger_2, count_jean_2, count_au_2,
          count_aothun_2, count_aokhoac_2, count_somi_2, count_hoodie_2
          ]
colors = ['purple']
title = 'Thống kê về các mặt hàng là Quần - Áo của Shop Routine'
xlabel = 'Các loại sản phẩm'
ylabel = 'Số lượng'
rotate = 45

ve_bieu_do_cot(title, colors, loai_sp, soluong, xlabel, ylabel, rotate)



"""#19110313 - Nguyễn Ngô Trung Hậu (Xuất ảnh và Kiểm Định)"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from PIL import Image
import requests
from io import BytesIO
from IPython.display import HTML
import glob
import random
import base64

"""##DATAFRAME CỦA CÁC SHOP

###SHOP BOUTIQUE
"""

data = 'x1.csv'
path = pd.read_csv(data)
df = pd.DataFrame(path)
df.head()

df['Gia'] = ''
df['Gia'] = df['Price'].str[:-1]
for i  in range(len(df['Gia'])):
  df['Gia'][i]=df['Price'].str[:-1][i].replace(".","")
df['Gia'] = df['Gia'].astype(int)
df['Gia'].dtype
df.head()

"""###SHOP TOTO"""

data1 = 'x2.csv'
path1 = pd.read_csv(data1)
df1 = pd.DataFrame(path1)
df1.head()

df1['Gia'] = ''
df1['Gia'] = df1['Price'].str[:-1]
for i  in range(len(df1['Gia'])):
  df1['Gia'][i]=df1['Price'].str[:-1][i].replace(".","")
df1['Gia'] = df1['Gia'].astype(int)
df1['Gia'].dtype
df1.head()

"""###SHOP ROUTINE"""

data2 = 'x3.csv'
path2 = pd.read_csv(data2)
df2 = pd.DataFrame(path2)
df2.head()

df2['Gia'] = ''
df2['Gia'] = df2['Price'].str[:-1]
for i  in range(len(df2['Gia'])):
  df2['Gia'][i]=df2['Price'].str[:-1][i].replace(".","")
df2['Gia'] = df2['Gia'].astype(int)
df2['Gia'].dtype
df2.head()

"""##TÌM KHOẢNG TIN CẬY CHO TRUNG BÌNH CỦA DỮ LIỆU"""

import statistics as sta
import numpy as np
import math
import scipy.stats
def mean_confidence_interval(data):
    #Tính độ dài của dữ liệu
    n=len(data)
    #Nhập độ lệch chuẩn tổng thể
    do_lech_chuan_tt=float(input("Nhap do lech chuan cua tong the(Neu chua biet do lech chuan cua tong the thi nhap 0): "))
    #Tính mean
    sample_mean=sta.mean(data)
    #Tính độ lệch chuẩn mẫu 
    do_lech_chuan=math.sqrt(sta.variance(data))
    #Nhập độ tin cậy cần tính
    confidence=int(input("Nhap do tin cay can tinh: "))
    alpha=1-(confidence/100)
    #Các trường hợp tính độ tin cậy
    #Trường hợp biết độ lệch chuẩn của tổng thể
    if do_lech_chuan_tt!=0:
        # Tính xác xuất giá trị nằm bên dưới  z-value trong phân phối chuẩn
        z=1-(alpha/2) 
        #Tinh z-value
        z_value=scipy.stats.norm.ppf(z)
        #Tính dung sai
        e=z_value*(do_lech_chuan_tt/math.sqrt(n))
        #Tính khoảng tin cậy
        confidence_interval=(sample_mean-e,sample_mean+e)
        #Trả về khoảng tin cậy
        print(confidence_interval)
    #Trường hợp chưa biết độ lệch chuẩn của tổng thể
    else:
        #Trường hợp mẫu lớn
        if n>30 or n==30:
            # Tính xác xuất giá trị nằm bên dưới  z-value trong phân phối chuan
            z=1-(alpha/2) 
            #Tinh z-value
            z_value=scipy.stats.norm.ppf(z)
            #Tính dung sai
            e=z_value*(do_lech_chuan/math.sqrt(n))
            #Tính khoảng tin cậy
            confidence_interval=(sample_mean-e,sample_mean+e)
            #Trả về khoảng tin cậy
            print(confidence_interval)
        #Trường hợp mẫu nhỏ
        else:
            #Tính bậc tự do 
            tu_do=n-1
            # Tính xác xuất giá trị nằm bên dưới  t-value trong phân phối t
            t=1-(alpha/2) 
            #Tinh z-value
            t_value=scipy.stats.t.ppf(t,tu_do)
            #Tính dung sai
            e=t_value*(do_lech_chuan/math.sqrt(n))
            #Tính khoảng tin cậy
            confidence_interval=(sample_mean-e,sample_mean+e)
            #Trả về khoảng tin cậy
            print(confidence_interval)

"""##TÌM KHOẢNG TIN CẬY CHO TRUNG BÌNH VỚI TRƯỜNG HỢP KHÔNG BIẾT ĐỘ LỆCH CHUẨN CỦA TỔNG THỂ VÀ KHOẢNG TIN CẬY 96%

###SHOP BOUTIQUE
"""

array=1.0*np.array(df['Gia'])
mean_confidence_interval(array)

"""###SHOP TOTO"""

array=1.0*np.array(df1['Gia'])
mean_confidence_interval(array)

"""###SHOP ROUTINE"""

array=1.0*np.array(df2['Gia'])
mean_confidence_interval(array)

"""##IN ẢNH CỦA LOẠI QUẦN ÁO

###SHOP BOUTIQUE
"""

name_ao = []
name_quan = []
name_loaikhac = []
for i in range(0,50):
  if df['PhanLoai'][i] ==0:
    n = df['Name'][i]
    name_ao.append(n)
  if df['PhanLoai'][i] ==1:
    n = df['Name'][i]
    name_quan.append(n)
  if df['PhanLoai'][i] ==2:
    n = df['Name'][i]
    name_loaikhac.append(n)
print(name_ao)
print(name_quan)
print(name_loaikhac)

price_ao = []
price_quan = []
price_loaikhac = []
for i in range(0,50):
  if df['PhanLoai'][i] ==0:
    n = df['Price'][i]
    price_ao.append(n)
  if df['PhanLoai'][i] ==1:
    n = df['Price'][i]
    price_quan.append(n)
  if df['PhanLoai'][i] ==2:
    n = df['Price'][i]
    price_loaikhac.append(n)
print(price_ao)
print(price_quan)
print(price_loaikhac)

image_ao = []
image_quan = []
image_loaikhac = []

for i  in range(0,50) :
  if df['PhanLoai'][i] == 0:
    i = Image.open(requests.get(df['Image'][i], stream=True).raw)
    image_ao.append(i)
for i  in range(0,50) :
  if df['PhanLoai'][i] == 1:
    i = Image.open(requests.get(df['Image'][i], stream=True).raw)
    image_quan.append(i)
for i  in range(0,50) :
  if df['PhanLoai'][i] == 2:
    i = Image.open(requests.get(df['Image'][i], stream=True).raw)
    image_loaikhac.append(i)
print(image_ao)
print(image_quan)
print(image_loaikhac)

ds_ao = {
    'name': name_ao,
    'image': image_ao,
    'price' : price_ao 
}
data_frame = pd.DataFrame(ds_ao)
display(data_frame)

ds_quan = {
    'name': name_quan,
    'image': image_quan,
    'price' : price_quan 
}
data_frame_1 = pd.DataFrame(ds_quan)
display(data_frame_1)

ds_loaikhac = {
    'name': name_loaikhac,
    'image': image_loaikhac,
    'price' : price_loaikhac 
}
data_frame_2 = pd.DataFrame(ds_loaikhac)
display(data_frame_2)

def image_base64(im):
  if isinstance(im, str):
    im = get_thumbnail(im)
  with BytesIO() as buffer:
    im.save(buffer, 'jpeg')
    return base64.b64encode(buffer.getvalue()).decode()
def image_formatter(im):
  return f'<img src="data:image/jpeg;base64,{image_base64(im)}">'

HTML(data_frame[['name', 'image','price']].to_html(formatters={'image': image_formatter}, escape=False))

HTML(data_frame_1[['name', 'image','price']].to_html(formatters={'image': image_formatter}, escape=False))

HTML(data_frame_2[['name', 'image','price']].to_html(formatters={'image': image_formatter}, escape=False))

"""###SHOP TOTO"""

name_ao_1 = []
name_quan_1 = []
name_loaikhac_1 = []
for i in range(0,50):
  if df1['PhanLoai'][i] ==0:
    n = df1['Name'][i]
    name_ao_1.append(n)
  if df1['PhanLoai'][i] ==1:
    n = df1['Name'][i]
    name_quan_1.append(n)
  if df1['PhanLoai'][i] ==2:
    n = df1['Name'][i]
    name_loaikhac_1.append(n)
print(name_ao_1)
print(name_quan_1)
print(name_loaikhac_1)

price_ao_1 = []
price_quan_1 = []
price_loaikhac_1 = []
for i in range(0,50):
  if df1['PhanLoai'][i] ==0:
    n = df1['Price'][i]
    price_ao_1.append(n)
  if df1['PhanLoai'][i] ==1:
    n = df1['Price'][i]
    price_quan_1.append(n)
  if df1['PhanLoai'][i] ==2:
    n = df1['Price'][i]
    price_loaikhac_1.append(n)
print(price_ao_1)
print(price_quan_1)
print(price_loaikhac_1)

image_ao_1 = []
image_quan_1 = []
image_loaikhac_1 = []

for i  in range(0,50) :
  if df1['PhanLoai'][i] == 0:
    i = Image.open(requests.get(df1['Image'][i], stream=True).raw)
    image_ao_1.append(i)
for i  in range(0,50) :
  if df1['PhanLoai'][i] == 1:
    i = Image.open(requests.get(df1['Image'][i], stream=True).raw)
    image_quan_1.append(i)
for i  in range(0,50) :
  if df1['PhanLoai'][i] == 2:
    i = Image.open(requests.get(df1['Image'][i], stream=True).raw)
    image_loaikhac_1.append(i)
print(image_ao_1)
print(image_quan_1)
print(image_loaikhac_1)

ds_ao_1 = {
    'name': name_ao_1,
    'image': image_ao_1,
    'price' : price_ao_1 
}
data_frame_toto = pd.DataFrame(ds_ao_1)
display(data_frame_toto)

ds_quan_1 = {
    'name': name_quan_1,
    'image': image_quan_1,
    'price' : price_quan_1 
}
data_frame_toto_1 = pd.DataFrame(ds_quan_1)
display(data_frame_toto_1)

ds_loaikhac_1 = {
    'name': name_loaikhac_1,
    'image': image_loaikhac_1,
    'price' : price_loaikhac_1 
}
data_frame_toto_2 = pd.DataFrame(ds_loaikhac_1)
display(data_frame_toto_1)

HTML(data_frame_toto[['name', 'image','price']].to_html(formatters={'image': image_formatter}, escape=False))

HTML(data_frame_toto_1[['name', 'image','price']].to_html(formatters={'image': image_formatter}, escape=False))

HTML(data_frame_toto_2[['name', 'image','price']].to_html(formatters={'image': image_formatter}, escape=False))

"""###SHOP ROUTNE

"""

name_ao_2 = []
name_quan_2 = []
name_loaikhac_2 = []
for i in range(0,50):
  if df2['PhanLoai'][i] ==0:
    n = df2['Name'][i]
    name_ao_2.append(n)
  if df2['PhanLoai'][i] ==1:
    n = df2['Name'][i]
    name_quan_2.append(n)
  if df2['PhanLoai'][i] ==2:
    n = df2['Name'][i]
    name_loaikhac_2.append(n)
print(name_ao_2)
print(name_quan_2)
print(name_loaikhac_2)

price_ao_2 = []
price_quan_2 = []
price_loaikhac_2 = []
for i in range(0,50):
  if df2['PhanLoai'][i] ==0:
    n = df2['Price'][i]
    price_ao_2.append(n)
  if df2['PhanLoai'][i] ==1:
    n = df2['Price'][i]
    price_quan_2.append(n)
  if df2['PhanLoai'][i] ==2:
    n = df2['Price'][i]
    price_loaikhac_2.append(n)
print(price_ao_2)
print(price_quan_2)
print(price_loaikhac_2)

image_ao_2 = []
image_quan_2 = []
image_loaikhac_2 = []

for i  in range(0,50) :
  if df2['PhanLoai'][i] == 0:
    i = Image.open(requests.get(df2['Image'][i], stream=True).raw)
    image_ao_2.append(i)
for i  in range(0,50) :
  if df2['PhanLoai'][i] == 1:
    i = Image.open(requests.get(df2['Image'][i], stream=True).raw)
    image_quan_2.append(i)
for i  in range(0,50) :
  if df2['PhanLoai'][i] == 2:
    i = Image.open(requests.get(df2['Image'][i], stream=True).raw)
    image_loaikhac_2.append(i)
print(image_ao_2)
print(image_quan_2)
print(image_loaikhac_2)

ds_ao_2 = {
    'name': name_ao_2,
    'image': image_ao_2,
    'price' : price_ao_2 
}
data_frame_routine = pd.DataFrame(ds_ao_2)
display(data_frame_routine)

ds_quan_2 = {
    'name': name_quan_2,
    'image': image_quan_2,
    'price' : price_quan_2 
}
data_frame_routine_1 = pd.DataFrame(ds_quan_2)
display(data_frame_routine_1)

ds_loaikhac_2 = {
    'name': name_loaikhac_2,
    'image': image_loaikhac_2,
    'price' : price_loaikhac_2 
}
data_frame_routine_2 = pd.DataFrame(ds_loaikhac_2)
display(data_frame_routine_2)

HTML(data_frame_routine[['name', 'image','price']].to_html(formatters={'image': image_formatter}, escape=False))

HTML(data_frame_routine_1[['name', 'image','price']].to_html(formatters={'image': image_formatter}, escape=False))

HTML(data_frame_routine_2[['name', 'image','price']].to_html(formatters={'image': image_formatter}, escape=False))

